// Generated by gencpp from file zhen_baxter_moveit/explore_reachResponse.msg
// DO NOT EDIT!


#ifndef ZHEN_BAXTER_MOVEIT_MESSAGE_EXPLORE_REACHRESPONSE_H
#define ZHEN_BAXTER_MOVEIT_MESSAGE_EXPLORE_REACHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zhen_baxter_moveit
{
template <class ContainerAllocator>
struct explore_reachResponse_
{
  typedef explore_reachResponse_<ContainerAllocator> Type;

  explore_reachResponse_()
    : succeed(false)  {
    }
  explore_reachResponse_(const ContainerAllocator& _alloc)
    : succeed(false)  {
    }



   typedef uint8_t _succeed_type;
  _succeed_type succeed;




  typedef boost::shared_ptr< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> const> ConstPtr;

}; // struct explore_reachResponse_

typedef ::zhen_baxter_moveit::explore_reachResponse_<std::allocator<void> > explore_reachResponse;

typedef boost::shared_ptr< ::zhen_baxter_moveit::explore_reachResponse > explore_reachResponsePtr;
typedef boost::shared_ptr< ::zhen_baxter_moveit::explore_reachResponse const> explore_reachResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zhen_baxter_moveit

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d9c3b918a0afafeULL;
  static const uint64_t static_value2 = 0x09791ef8d7853918ULL;
};

template<class ContainerAllocator>
struct DataType< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zhen_baxter_moveit/explore_reachResponse";
  }

  static const char* value(const ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool succeed\n\
\n\
";
  }

  static const char* value(const ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct explore_reachResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zhen_baxter_moveit::explore_reachResponse_<ContainerAllocator>& v)
  {
    s << indent << "succeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZHEN_BAXTER_MOVEIT_MESSAGE_EXPLORE_REACHRESPONSE_H
