// Generated by gencpp from file zhen_baxter_moveit/explore_reach.msg
// DO NOT EDIT!


#ifndef ZHEN_BAXTER_MOVEIT_MESSAGE_EXPLORE_REACH_H
#define ZHEN_BAXTER_MOVEIT_MESSAGE_EXPLORE_REACH_H

#include <ros/service_traits.h>


#include <zhen_baxter_moveit/explore_reachRequest.h>
#include <zhen_baxter_moveit/explore_reachResponse.h>


namespace zhen_baxter_moveit
{

struct explore_reach
{

typedef explore_reachRequest Request;
typedef explore_reachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct explore_reach
} // namespace zhen_baxter_moveit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zhen_baxter_moveit::explore_reach > {
  static const char* value()
  {
    return "9f0d7596b5227dcbe3cd716043ba03b1";
  }

  static const char* value(const ::zhen_baxter_moveit::explore_reach&) { return value(); }
};

template<>
struct DataType< ::zhen_baxter_moveit::explore_reach > {
  static const char* value()
  {
    return "zhen_baxter_moveit/explore_reach";
  }

  static const char* value(const ::zhen_baxter_moveit::explore_reach&) { return value(); }
};


// service_traits::MD5Sum< ::zhen_baxter_moveit::explore_reachRequest> should match 
// service_traits::MD5Sum< ::zhen_baxter_moveit::explore_reach > 
template<>
struct MD5Sum< ::zhen_baxter_moveit::explore_reachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zhen_baxter_moveit::explore_reach >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::explore_reachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zhen_baxter_moveit::explore_reachRequest> should match 
// service_traits::DataType< ::zhen_baxter_moveit::explore_reach > 
template<>
struct DataType< ::zhen_baxter_moveit::explore_reachRequest>
{
  static const char* value()
  {
    return DataType< ::zhen_baxter_moveit::explore_reach >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::explore_reachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zhen_baxter_moveit::explore_reachResponse> should match 
// service_traits::MD5Sum< ::zhen_baxter_moveit::explore_reach > 
template<>
struct MD5Sum< ::zhen_baxter_moveit::explore_reachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zhen_baxter_moveit::explore_reach >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::explore_reachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zhen_baxter_moveit::explore_reachResponse> should match 
// service_traits::DataType< ::zhen_baxter_moveit::explore_reach > 
template<>
struct DataType< ::zhen_baxter_moveit::explore_reachResponse>
{
  static const char* value()
  {
    return DataType< ::zhen_baxter_moveit::explore_reach >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::explore_reachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZHEN_BAXTER_MOVEIT_MESSAGE_EXPLORE_REACH_H
