// Generated by gencpp from file zhen_baxter_moveit/move_to_target_pose.msg
// DO NOT EDIT!


#ifndef ZHEN_BAXTER_MOVEIT_MESSAGE_MOVE_TO_TARGET_POSE_H
#define ZHEN_BAXTER_MOVEIT_MESSAGE_MOVE_TO_TARGET_POSE_H

#include <ros/service_traits.h>


#include <zhen_baxter_moveit/move_to_target_poseRequest.h>
#include <zhen_baxter_moveit/move_to_target_poseResponse.h>


namespace zhen_baxter_moveit
{

struct move_to_target_pose
{

typedef move_to_target_poseRequest Request;
typedef move_to_target_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_to_target_pose
} // namespace zhen_baxter_moveit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zhen_baxter_moveit::move_to_target_pose > {
  static const char* value()
  {
    return "24c7d94dc9830b995b4900bda600f60c";
  }

  static const char* value(const ::zhen_baxter_moveit::move_to_target_pose&) { return value(); }
};

template<>
struct DataType< ::zhen_baxter_moveit::move_to_target_pose > {
  static const char* value()
  {
    return "zhen_baxter_moveit/move_to_target_pose";
  }

  static const char* value(const ::zhen_baxter_moveit::move_to_target_pose&) { return value(); }
};


// service_traits::MD5Sum< ::zhen_baxter_moveit::move_to_target_poseRequest> should match 
// service_traits::MD5Sum< ::zhen_baxter_moveit::move_to_target_pose > 
template<>
struct MD5Sum< ::zhen_baxter_moveit::move_to_target_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zhen_baxter_moveit::move_to_target_pose >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::move_to_target_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zhen_baxter_moveit::move_to_target_poseRequest> should match 
// service_traits::DataType< ::zhen_baxter_moveit::move_to_target_pose > 
template<>
struct DataType< ::zhen_baxter_moveit::move_to_target_poseRequest>
{
  static const char* value()
  {
    return DataType< ::zhen_baxter_moveit::move_to_target_pose >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::move_to_target_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zhen_baxter_moveit::move_to_target_poseResponse> should match 
// service_traits::MD5Sum< ::zhen_baxter_moveit::move_to_target_pose > 
template<>
struct MD5Sum< ::zhen_baxter_moveit::move_to_target_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zhen_baxter_moveit::move_to_target_pose >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::move_to_target_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zhen_baxter_moveit::move_to_target_poseResponse> should match 
// service_traits::DataType< ::zhen_baxter_moveit::move_to_target_pose > 
template<>
struct DataType< ::zhen_baxter_moveit::move_to_target_poseResponse>
{
  static const char* value()
  {
    return DataType< ::zhen_baxter_moveit::move_to_target_pose >::value();
  }
  static const char* value(const ::zhen_baxter_moveit::move_to_target_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZHEN_BAXTER_MOVEIT_MESSAGE_MOVE_TO_TARGET_POSE_H
